//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public int PrdId { get; set; }
        public int QtySold { get; set; }
        public float Discount { get; set; }
        public int ProductPid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
